import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Simple site header: header reserved for page-level controls (Nav will show auth) */}
        <header style={{ display: "flex", justifyContent: "flex-end", padding: 12 }}>
          {/* AuthStatus intentionally removed from the top-right; Nav will render it near the navbar */}
        </header>

        {children}
      </body>
    </html>
  );
}
